version: '3'

services:
  app:
    restart: always
    build:
      context: ./node
    container_name: app
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
      - db
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: "node ./index.js"

  nginx:
    restart: always
    build:
      context: ./nginx
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - app

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./node/.docker/mysql:/docker-entrypoint-initdb.d
    networks:
      - node-network
    command: --innodb-use-native-aio=0
    environment:
      MYSQL_DATABASE: nodedb
      MYSQL_ROOT_PASSWORD: root

networks:
  node-network:
    driver: bridge 
